from datetime import datetime

print(datetime.now().date())

"""
Ok, we need a method that copies file and deletes empty lines from it.
Next, what?
We need to combine result of that method applied to our file, with 
calendar generated by other method.
Then we need way to retrieve data from this combination in a right way
"""

